ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8081
        
db:
  url: ""
  user: ""
  pass: 

security:
  jwt:
    issuer: ""
    audience: ""
    secret: ""