services:
  postgres:
    build: .                # <--- en vez de "image: postgres:16"
    container_name: Entrevista_APP
    restart: always
    environment:
      POSTGRES_DB: DBentrevista
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
